language: php

php:
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
